export const EQUIPMENT_OPTIONS = [
  { label: "Electric Wheelchair", value: "electric_wheelchair", description: "Powered mobility device" },
  { label: "Manual Wheelchair", value: "manual_wheelchair", description: "Self-propelled mobility device" },
  { label: "Walking frame", value: "walking_frame", description: "Static walking aid" },
  { label: "Tripod frame", value: "tripod_frame", description: "Three-legged walking aid" },
  { label: "Wheeled walker", value: "wheeled_walker", description: "Walking aid with wheels" },
  { label: "Walking stick", value: "walking_stick", description: "Single-point walking aid" },
  { label: "Hospital bed", value: "hospital_bed", description: "Adjustable medical bed" },
  { label: "Rise recline Chair", value: "rise_recline_chair", description: "Powered lifting chair" },
  { label: "Bath lift", value: "bath_lift", description: "Bathing assistance device" },
  { label: "Shower seat", value: "shower_seat", description: "Seated showering aid" },
  { label: "Static Commode", value: "static_commode", description: "Fixed toilet aid" },
  { label: "Glider Commode", value: "glider_commode", description: "Mobile toilet aid" },
  { label: "Ceiling track hoist", value: "ceiling_track_hoist", description: "Overhead lifting system" },
  { label: "Mobile hoist", value: "mobile_hoist", description: "Portable lifting device" },
  { label: "Rotunda", value: "rotunda", description: "Rotating transfer aid" },
  { label: "Standing hoist", value: "standing_hoist", description: "Standing assistance device" },
  { label: "Stair lift", value: "stair_lift", description: "Stairway mobility device" },
  { label: "Perching stool", value: "perching_stool", description: "Semi-standing seat" },
  { label: "Raised toilet seat", value: "raised_toilet_seat", description: "Toilet height adapter" },
  { label: "Banana board", value: "banana_board", description: "Transfer board" },
  { label: "Grab Rails", value: "grab_rails", description: "Safety support rails" },
  { label: "Other", value: "other", description: "Other equipment not listed" },
];