import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";

interface MedicationReportData {
  clientName: string;
  clientEmail?: string | null;
  clientPhone?: string | null;
  clientDateOfBirth?: string | null;
  clientGender?: string | null;
  clientAddress?: string | null;
  medications: Array<{
    name: string;
    dosage: string;
    frequency: string;
    start_date: string;
    end_date?: string | null;
    status: string;
    notes?: string | null;
    givenBy?: string | null;
    givenByRole?: string | null;
  }>;
  branchName?: string;
  generatedBy?: string;
}

export const generateMedicationReportPDF = (data: MedicationReportData): void => {
  const doc = new jsPDF();
  
  // Header with branding
  doc.setFontSize(22);
  doc.setTextColor(0, 83, 156);
  doc.text("Med-Infinite", 20, 20);
  
  // Branch name
  if (data.branchName) {
    doc.setFontSize(11);
    doc.setTextColor(100, 100, 100);
    doc.text(data.branchName, 20, 28);
  }
  
  // Report title
  doc.setFontSize(18);
  doc.setTextColor(0, 0, 0);
  doc.text("Medication Report", 20, 42);
  
  // Horizontal line
  doc.setDrawColor(0, 83, 156);
  doc.setLineWidth(0.5);
  doc.line(20, 46, 190, 46);
  
  // Generation info
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on: ${format(new Date(), "dd MMM yyyy, HH:mm")}`, 20, 54);
  if (data.generatedBy) {
    doc.text(`Generated by: ${data.generatedBy}`, 120, 54);
  }
  
  // Client Details Section
  doc.setFontSize(14);
  doc.setTextColor(0, 83, 156);
  doc.text("Client Details", 20, 68);
  
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  let yPos = 78;
  
  const addClientDetail = (label: string, value: string | null | undefined) => {
    if (value) {
      doc.setFont("helvetica", "bold");
      doc.text(`${label}:`, 20, yPos);
      doc.setFont("helvetica", "normal");
      doc.text(value, 55, yPos);
      yPos += 7;
    }
  };
  
  addClientDetail("Name", data.clientName);
  addClientDetail("Email", data.clientEmail);
  addClientDetail("Phone", data.clientPhone);
  if (data.clientDateOfBirth) {
    try {
      addClientDetail("Date of Birth", format(new Date(data.clientDateOfBirth), "dd MMM yyyy"));
    } catch {
      addClientDetail("Date of Birth", data.clientDateOfBirth);
    }
  }
  addClientDetail("Gender", data.clientGender ? data.clientGender.charAt(0).toUpperCase() + data.clientGender.slice(1) : null);
  addClientDetail("Address", data.clientAddress);
  
  // Medications Table Section
  yPos += 10;
  doc.setFontSize(14);
  doc.setTextColor(0, 83, 156);
  doc.text("Medication History", 20, yPos);
  
  if (data.medications.length === 0) {
    yPos += 15;
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("No medications recorded for this client.", 20, yPos);
  } else {
    // Table columns and data
    const tableColumn = ["Medication", "Dosage", "Frequency", "Start Date", "End Date", "Status", "Given By"];
    const tableRows = data.medications.map(med => {
      let startDateFormatted = med.start_date;
      let endDateFormatted = med.end_date || "Ongoing";
      
      try {
        startDateFormatted = format(new Date(med.start_date), "dd MMM yyyy");
      } catch {
        // Keep original value if date parsing fails
      }
      
      if (med.end_date) {
        try {
          endDateFormatted = format(new Date(med.end_date), "dd MMM yyyy");
        } catch {
          // Keep original value if date parsing fails
        }
      }
      
      const givenByDisplay = med.givenBy 
        ? `${med.givenBy}${med.givenByRole ? ` (${med.givenByRole})` : ''}`
        : '—';
      
      return [
        med.name,
        med.dosage,
        med.frequency,
        startDateFormatted,
        endDateFormatted,
        med.status.charAt(0).toUpperCase() + med.status.slice(1),
        givenByDisplay
      ];
    });
    
    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: yPos + 8,
      theme: 'grid',
      styles: { 
        fontSize: 8, 
        cellPadding: 3,
        overflow: 'linebreak'
      },
      headStyles: {
        fillColor: [0, 83, 156],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        halign: 'center'
      },
      columnStyles: {
        0: { cellWidth: 30 },
        1: { cellWidth: 22 },
        2: { cellWidth: 25 },
        3: { cellWidth: 22 },
        4: { cellWidth: 22 },
        5: { cellWidth: 20 },
        6: { cellWidth: 35 }
      },
      alternateRowStyles: { fillColor: [245, 247, 250] },
    });
    
    // Summary section
    const finalY = (doc as any).lastAutoTable.finalY + 15;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 83, 156);
    doc.text("Summary", 20, finalY);
    
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Total Medications: ${data.medications.length}`, 20, finalY + 10);
    
    // Status breakdown
    const statusCounts = data.medications.reduce((acc, med) => {
      const statusKey = med.status.toLowerCase();
      acc[statusKey] = (acc[statusKey] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);
    
    let statusY = finalY + 18;
    Object.entries(statusCounts).forEach(([status, count]) => {
      const statusLabel = status.charAt(0).toUpperCase() + status.slice(1);
      doc.text(`• ${statusLabel}: ${count}`, 25, statusY);
      statusY += 6;
    });
  }
  
  // Footer with page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(130, 130, 130);
    doc.text(
      `Page ${i} of ${pageCount} | Med-Infinite - Confidential`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }
  
  // Save the PDF
  const sanitizedClientName = data.clientName.replace(/[^a-zA-Z0-9]/g, "_");
  const fileName = `Medication_Report_${sanitizedClientName}_${format(new Date(), "yyyy-MM-dd")}.pdf`;
  doc.save(fileName);
};
