import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import { DocumentItem, StaffComplianceRow } from '@/hooks/useStaffComplianceMatrix';

// Individual staff compliance PDF
export const generateStaffCompliancePDF = (
  staffName: string,
  breakdown: {
    expiredItems: DocumentItem[];
    expiringItems: DocumentItem[];
    pendingItems: DocumentItem[];
    notUpdatedItems: DocumentItem[];
    compliantItems: DocumentItem[];
  },
  branchName: string
): void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  let yPosition = 20;

  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Staff Compliance Report', pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 10;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(branchName, pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 15;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`Staff Member: ${staffName}`, 14, yPosition);
  
  yPosition += 8;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Report Generated: ${format(new Date(), 'dd/MM/yyyy HH:mm')}`, 14, yPosition);
  
  yPosition += 15;

  // Summary Section
  const totalIssues = 
    breakdown.expiredItems.length + 
    breakdown.expiringItems.length + 
    breakdown.pendingItems.length +
    breakdown.notUpdatedItems.length;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 14, yPosition);
  yPosition += 8;
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Issues: ${totalIssues}`, 14, yPosition);
  yPosition += 6;
  doc.text(`Compliant Items: ${breakdown.compliantItems.length}`, 14, yPosition);
  yPosition += 10;

  // Helper function to add section with table
  const addSection = (
    title: string,
    items: DocumentItem[],
    color: [number, number, number]
  ) => {
    if (items.length === 0) return;

    // Check if we need a new page
    if (yPosition > pageHeight - 60) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(color[0], color[1], color[2]);
    doc.text(title, 14, yPosition);
    doc.setTextColor(0, 0, 0);
    yPosition += 5;

    const tableData = items.map(item => [
      item.name.length > 35 ? item.name.substring(0, 32) + '...' : item.name,
      item.type === 'document' ? 'Document' : 'Essential',
      item.category || 'N/A',
      item.daysUntilExpiry !== null
        ? item.daysUntilExpiry < 0
          ? `Expired ${Math.abs(item.daysUntilExpiry)}d ago`
          : item.daysUntilExpiry === 0
          ? 'Expires today'
          : `${item.daysUntilExpiry}d remaining`
        : item.isNotUpdated
        ? 'Not Updated'
        : item.status || 'N/A',
      item.required ? 'Yes' : 'No',
    ]);

    autoTable(doc, {
      startY: yPosition,
      head: [['Item Name', 'Type', 'Category', 'Status', 'Required']],
      body: tableData,
      theme: 'striped',
      headStyles: {
        fillColor: color,
        textColor: [255, 255, 255],
        fontSize: 9,
        fontStyle: 'bold',
      },
      bodyStyles: {
        fontSize: 8,
      },
      columnStyles: {
        0: { cellWidth: 60 },
        1: { cellWidth: 25 },
        2: { cellWidth: 30 },
        3: { cellWidth: 40 },
        4: { cellWidth: 20 },
      },
      margin: { left: 14, right: 14 },
    });

    yPosition = (doc as any).lastAutoTable.finalY + 10;
  };

  // Add sections
  addSection(
    `Expired Items (${breakdown.expiredItems.length})`,
    breakdown.expiredItems,
    [239, 68, 68] // Red
  );

  addSection(
    `Not Updated Required Items (${breakdown.notUpdatedItems.length})`,
    breakdown.notUpdatedItems,
    [220, 38, 38] // Dark red
  );

  addSection(
    `Expiring Soon (${breakdown.expiringItems.length})`,
    breakdown.expiringItems,
    [245, 158, 11] // Amber
  );

  addSection(
    `Pending Required Items (${breakdown.pendingItems.length})`,
    breakdown.pendingItems,
    [251, 191, 36] // Yellow
  );

  addSection(
    `Compliant Items (${breakdown.compliantItems.length})`,
    breakdown.compliantItems,
    [34, 197, 94] // Green
  );

  // Footer on last page
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${totalPages} | Generated by Med-Infinite Care System`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  doc.save(`${staffName.replace(/\s+/g, '_')}_Compliance_Report_${format(new Date(), 'yyyyMMdd')}.pdf`);
};

// Bulk staff compliance PDF
export const generateBulkStaffCompliancePDF = (
  staffRows: StaffComplianceRow[],
  branchName: string
): void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  let yPosition = 30;

  // Cover Page
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Staff Compliance Report', pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 15;
  doc.setFontSize(16);
  doc.text(branchName, pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 30;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Staff Members: ${staffRows.length}`, pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 10;
  doc.text(`Report Date: ${format(new Date(), 'dd MMMM yyyy')}`, pageWidth / 2, yPosition, { align: 'center' });
  
  // Overall Summary on cover
  yPosition += 20;
  const totalExpired = staffRows.reduce((sum, s) => sum + s.detailedBreakdown.expiredItems.length, 0);
  const totalExpiring = staffRows.reduce((sum, s) => sum + s.detailedBreakdown.expiringItems.length, 0);
  const totalNotUpdated = staffRows.reduce((sum, s) => sum + s.detailedBreakdown.notUpdatedItems.length, 0);
  const totalPending = staffRows.reduce((sum, s) => sum + s.detailedBreakdown.pendingItems.length, 0);
  const totalCompliant = staffRows.reduce((sum, s) => sum + s.detailedBreakdown.compliantItems.length, 0);
  const compliantStaff = staffRows.filter(s => s.complianceLevel === 'compliant').length;
  const atRiskStaff = staffRows.filter(s => s.complianceLevel === 'at-risk').length;
  const nonCompliantStaff = staffRows.filter(s => s.complianceLevel === 'non-compliant').length;

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Branch Summary', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 12;
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const summaryLines = [
    `Compliant Staff: ${compliantStaff} (${((compliantStaff / staffRows.length) * 100).toFixed(1)}%)`,
    `At Risk Staff: ${atRiskStaff} (${((atRiskStaff / staffRows.length) * 100).toFixed(1)}%)`,
    `Non-Compliant Staff: ${nonCompliantStaff} (${((nonCompliantStaff / staffRows.length) * 100).toFixed(1)}%)`,
    '',
    `Total Expired Items: ${totalExpired}`,
    `Total Not Updated Items: ${totalNotUpdated}`,
    `Total Expiring Soon: ${totalExpiring}`,
    `Total Pending Items: ${totalPending}`,
    `Total Compliant Items: ${totalCompliant}`,
  ];

  summaryLines.forEach(line => {
    doc.text(line, pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 6;
  });

  // Table of Contents
  doc.addPage();
  yPosition = 20;
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Table of Contents', 14, yPosition);
  yPosition += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  let currentPage = 3;
  
  staffRows.forEach((staff, index) => {
    if (yPosition > pageHeight - 30) {
      doc.addPage();
      yPosition = 20;
    }
    
    doc.text(`${index + 1}. ${staff.staffName}`, 20, yPosition);
    doc.text(`Page ${currentPage}`, pageWidth - 30, yPosition);
    yPosition += 7;
    currentPage += 1;
  });

  // Individual Staff Sections
  staffRows.forEach((staff, index) => {
    doc.addPage();
    yPosition = 20;

    // Staff header
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(`${index + 1}. ${staff.staffName}`, 14, yPosition);
    
    yPosition += 10;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    const issues = 
      staff.detailedBreakdown.expiredItems.length +
      staff.detailedBreakdown.expiringItems.length +
      staff.detailedBreakdown.pendingItems.length +
      staff.detailedBreakdown.notUpdatedItems.length;

    doc.text(`Overall Score: ${staff.overallScore}%`, 14, yPosition);
    yPosition += 6;
    doc.text(`Compliance Level: ${staff.complianceLevel.charAt(0).toUpperCase() + staff.complianceLevel.slice(1)}`, 14, yPosition);
    yPosition += 6;
    doc.text(`Total Issues: ${issues}`, 14, yPosition);
    yPosition += 6;
    doc.text(`Compliant Items: ${staff.detailedBreakdown.compliantItems.length}`, 14, yPosition);
    yPosition += 12;

    // Add condensed sections
    const addStaffSection = (title: string, items: DocumentItem[], color: [number, number, number]) => {
      if (items.length === 0) return;

      if (yPosition > pageHeight - 40) {
        doc.addPage();
        yPosition = 20;
      }

      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(color[0], color[1], color[2]);
      doc.text(`${title} (${items.length})`, 14, yPosition);
      doc.setTextColor(0, 0, 0);
      yPosition += 5;

      const tableData = items.slice(0, 10).map(item => [
        item.name.length > 40 ? item.name.substring(0, 37) + '...' : item.name,
        item.type === 'document' ? 'Doc' : 'Ess',
        item.daysUntilExpiry !== null
          ? item.daysUntilExpiry < 0
            ? `Exp ${Math.abs(item.daysUntilExpiry)}d`
            : `${item.daysUntilExpiry}d`
          : item.isNotUpdated
          ? 'Not Updated'
          : item.status || 'N/A',
      ]);

      autoTable(doc, {
        startY: yPosition,
        head: [['Item', 'Type', 'Status']],
        body: tableData,
        theme: 'grid',
        headStyles: {
          fillColor: color,
          textColor: [255, 255, 255],
          fontSize: 8,
          fontStyle: 'bold',
        },
        bodyStyles: {
          fontSize: 7,
        },
        columnStyles: {
          0: { cellWidth: 110 },
          1: { cellWidth: 25 },
          2: { cellWidth: 45 },
        },
        margin: { left: 14, right: 14 },
      });

      yPosition = (doc as any).lastAutoTable.finalY + 8;

      if (items.length > 10) {
        doc.setFontSize(8);
        doc.setTextColor(128, 128, 128);
        doc.text(`... and ${items.length - 10} more items`, 14, yPosition);
        doc.setTextColor(0, 0, 0);
        yPosition += 8;
      }
    };

    addStaffSection('Expired', staff.detailedBreakdown.expiredItems, [239, 68, 68]);
    addStaffSection('Not Updated', staff.detailedBreakdown.notUpdatedItems, [220, 38, 38]);
    addStaffSection('Expiring Soon', staff.detailedBreakdown.expiringItems, [245, 158, 11]);
    addStaffSection('Pending', staff.detailedBreakdown.pendingItems, [251, 191, 36]);
    addStaffSection('Compliant', staff.detailedBreakdown.compliantItems, [34, 197, 94]);
  });

  // Footer on all pages
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${totalPages} | ${branchName} | Generated ${format(new Date(), 'dd/MM/yyyy')}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  doc.save(`${branchName.replace(/\s+/g, '_')}_Staff_Compliance_Bulk_Report_${format(new Date(), 'yyyyMMdd')}.pdf`);
};
