
import React, { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { CalendarIcon, FileText } from "lucide-react";
import { format } from "date-fns";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { useToast } from "@/hooks/use-toast";
import { Calendar } from "@/components/ui/calendar";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { cn } from "@/lib/utils";
import { useBranchStaff } from "@/hooks/useBranchStaff";
import { useParams } from "react-router-dom";

const formSchema = z.object({
  title: z.string().min(3, "Title must be at least 3 characters"),
  provider_type: z.enum(["staff", "external"], {
    required_error: "Please select a provider type",
  }),
  staff_id: z.string().optional(),
  provider_name: z.string().optional(),
  start_date: z.date({
    required_error: "Start date is required",
  }),
  end_date: z.date().optional(),
  review_date: z.date().optional(),
}).refine((data) => {
  if (data.provider_type === "staff") {
    return !!data.staff_id;
  } else {
    return !!data.provider_name && data.provider_name.trim().length > 0;
  }
}, {
  message: "Please select a staff member or enter an external provider name",
  path: ["provider_name"],
});

type FormValues = z.infer<typeof formSchema>;

interface CreateCarePlanDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSave: (carePlan: FormValues) => void;
  clientId?: string; // Make clientId optional for backward compatibility
}

export function CreateCarePlanDialog({ 
  open, 
  onOpenChange, 
  onSave,
  clientId 
}: CreateCarePlanDialogProps) {
  const { toast } = useToast();
  const { id: branchId } = useParams();
  const [providerType, setProviderType] = useState<"staff" | "external">("staff");
  const queryClient = useQueryClient();
  
  const { data: branchStaff = [], isLoading: isLoadingStaff } = useBranchStaff(branchId || '');

  const form = useForm<FormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      title: "",
      provider_type: "staff",
      staff_id: "",
      provider_name: "",
      start_date: new Date(),
      end_date: undefined,
      review_date: undefined,
    },
  });

  const createCarePlanMutation = useMutation({
    mutationFn: async (carePlanData: FormValues) => {
      // Use clientId from props if available, otherwise this should be called from client context
      const targetClientId = clientId;
      
      if (!targetClientId) {
        throw new Error("Client ID is required to create a care plan");
      }

      // Prepare the data based on provider type
      const insertData: any = {
        client_id: targetClientId,
        title: carePlanData.title,
        start_date: carePlanData.start_date.toISOString().split('T')[0],
        end_date: carePlanData.end_date ? carePlanData.end_date.toISOString().split('T')[0] : null,
        review_date: carePlanData.review_date ? carePlanData.review_date.toISOString().split('T')[0] : null,
        status: 'active'
        // Note: display_id will be auto-generated by the database trigger
      };

      if (carePlanData.provider_type === 'staff' && carePlanData.staff_id) {
        // Find the staff member to get their name
        const staffMember = branchStaff.find(staff => staff.id === carePlanData.staff_id);
        insertData.staff_id = carePlanData.staff_id;
        insertData.provider_name = staffMember ? `${staffMember.first_name} ${staffMember.last_name}` : 'Unknown Staff';
      } else {
        // External provider
        insertData.provider_name = carePlanData.provider_name;
      }

      const { data, error } = await supabase
        .from('client_care_plans')
        .insert([insertData])
        .select('*, display_id')
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['care-plans'] });
      if (clientId) {
        queryClient.invalidateQueries({ queryKey: ['client-care-plans', clientId] });
      }
      toast({
        title: "Care plan created",
        description: `Care plan ${data.display_id} has been created successfully`,
      });
      form.reset();
      onOpenChange(false);
    },
    onError: (error) => {
      console.error('Error creating care plan:', error);
      toast({
        title: "Error",
        description: "Failed to create care plan. Please try again.",
        variant: "destructive",
      });
    }
  });

  function onSubmit(data: FormValues) {
    createCarePlanMutation.mutate(data);
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-blue-600">
            <FileText className="h-5 w-5" />
            Create Care Plan
          </DialogTitle>
          <DialogDescription>
            Create a new care plan for the selected client
          </DialogDescription>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            <FormField
              control={form.control}
              name="title"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Care Plan Title</FormLabel>
                  <FormControl>
                    <Input placeholder="Physical Therapy Plan" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="provider_type"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Provider Type</FormLabel>
                  <Select 
                    onValueChange={(value) => {
                      field.onChange(value);
                      setProviderType(value as "staff" | "external");
                      // Clear the other provider field when switching types
                      if (value === "staff") {
                        form.setValue("provider_name", "");
                      } else {
                        form.setValue("staff_id", "");
                      }
                    }} 
                    defaultValue={field.value}
                  >
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Select provider type" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      <SelectItem value="staff">Internal Staff Member</SelectItem>
                      <SelectItem value="external">External Provider</SelectItem>
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />

            {providerType === "staff" && (
              <FormField
                control={form.control}
                name="staff_id"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Assigned Staff Member</FormLabel>
                    <Select 
                      onValueChange={field.onChange} 
                      defaultValue={field.value}
                      disabled={isLoadingStaff}
                    >
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder={isLoadingStaff ? "Loading staff..." : "Select a staff member"} />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {branchStaff.map((staff) => (
                          <SelectItem key={staff.id} value={staff.id}>
                            {staff.first_name} {staff.last_name}
                            {staff.specialization && ` - ${staff.specialization}`}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
            )}

            {providerType === "external" && (
              <FormField
                control={form.control}
                name="provider_name"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>External Provider Name</FormLabel>
                    <FormControl>
                      <Input placeholder="Dr. John Smith" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            )}

            <FormField
              control={form.control}
              name="start_date"
              render={({ field }) => (
                <FormItem className="flex flex-col">
                  <FormLabel>Start Date</FormLabel>
                  <Popover>
                    <PopoverTrigger asChild>
                      <FormControl>
                        <Button
                          variant={"outline"}
                          className={cn(
                            "w-full pl-3 text-left font-normal",
                            !field.value && "text-muted-foreground"
                          )}
                        >
                          {field.value ? (
                            format(field.value, "PPP")
                          ) : (
                            <span>Pick a date</span>
                          )}
                          <CalendarIcon className="ml-auto h-4 w-4 opacity-50" />
                        </Button>
                      </FormControl>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0" align="start">
                      <Calendar
                        mode="single"
                        selected={field.value}
                        onSelect={field.onChange}
                        initialFocus
                      />
                    </PopoverContent>
                  </Popover>
                  <FormMessage />
                </FormItem>
              )}
            />

            <div className="grid grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="end_date"
                render={({ field }) => (
                  <FormItem className="flex flex-col">
                    <FormLabel>End Date (Optional)</FormLabel>
                    <Popover>
                      <PopoverTrigger asChild>
                        <FormControl>
                          <Button
                            variant={"outline"}
                            className={cn(
                              "w-full pl-3 text-left font-normal",
                              !field.value && "text-muted-foreground"
                            )}
                          >
                            {field.value ? (
                              format(field.value, "PPP")
                            ) : (
                              <span>Pick a date</span>
                            )}
                            <CalendarIcon className="ml-auto h-4 w-4 opacity-50" />
                          </Button>
                        </FormControl>
                      </PopoverTrigger>
                      <PopoverContent className="w-auto p-0" align="start">
                        <Calendar
                          mode="single"
                          selected={field.value}
                          onSelect={field.onChange}
                          disabled={(date) => date < new Date()}
                          initialFocus
                        />
                      </PopoverContent>
                    </Popover>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="review_date"
                render={({ field }) => (
                  <FormItem className="flex flex-col">
                    <FormLabel>Review Date (Optional)</FormLabel>
                    <Popover>
                      <PopoverTrigger asChild>
                        <FormControl>
                          <Button
                            variant={"outline"}
                            className={cn(
                              "w-full pl-3 text-left font-normal",
                              !field.value && "text-muted-foreground"
                            )}
                          >
                            {field.value ? (
                              format(field.value, "PPP")
                            ) : (
                              <span>Pick a date</span>
                            )}
                            <CalendarIcon className="ml-auto h-4 w-4 opacity-50" />
                          </Button>
                        </FormControl>
                      </PopoverTrigger>
                      <PopoverContent className="w-auto p-0" align="start">
                        <Calendar
                          mode="single"
                          selected={field.value}
                          onSelect={field.onChange}
                          disabled={(date) => date < new Date()}
                          initialFocus
                        />
                      </PopoverContent>
                    </Popover>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <DialogFooter className="gap-2 sm:gap-0">
              <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
                Cancel
              </Button>
              <Button type="submit" disabled={createCarePlanMutation.isPending}>
                {createCarePlanMutation.isPending ? "Creating..." : "Create Care Plan"}
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
