-- Add missing permission columns to admin_permissions table to match UI expectations
ALTER TABLE public.admin_permissions 
ADD COLUMN IF NOT EXISTS dashboard boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS bookings boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS clients boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS carers boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS reviews boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS communication boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS medication boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS workflow boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS key_parameters boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS care_plan boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS under_review_care_plan boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS agreements boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS events_logs boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS attendance boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS form_builder boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS documents boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS notifications boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS library boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS third_party boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS reports boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS system boolean DEFAULT true;

-- Update existing records to set all new columns to true (maintain existing access)
UPDATE public.admin_permissions SET
  dashboard = COALESCE(dashboard, true),
  bookings = COALESCE(bookings, true),
  clients = COALESCE(clients, true),
  carers = COALESCE(carers, true),
  reviews = COALESCE(reviews, true),
  communication = COALESCE(communication, true),
  medication = COALESCE(medication, true),
  workflow = COALESCE(workflow, true),
  key_parameters = COALESCE(key_parameters, true),
  care_plan = COALESCE(care_plan, true),
  under_review_care_plan = COALESCE(under_review_care_plan, true),
  agreements = COALESCE(agreements, true),
  events_logs = COALESCE(events_logs, true),
  attendance = COALESCE(attendance, true),
  form_builder = COALESCE(form_builder, true),
  documents = COALESCE(documents, true),
  notifications = COALESCE(notifications, true),
  library = COALESCE(library, true),
  third_party = COALESCE(third_party, true),
  reports = COALESCE(reports, true),
  system = COALESCE(system, true);